version: "3.8"
networks:
  default:
    name: docker-default-network
    external:
      true
      
services:

  oracle:
    image: docker.io/gvenzl/oracle-free:23-slim-faststart
#    image: container-registry.oracle.com/database/express:latest
    environment:
      ORACLE_PASSWORD: password
    ports:
      - 5500:5500
      - 1521:1521
