version: "3.8"
networks:
  default:
    name: docker-default-network
    external: true

services:
  sonar:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    # environment:
      # - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      # - SONARQUBE_JDBC_USERNAME=sonar
      # - SONARQUBE_JDBC_PASSWORD=sonar