'%dev':
    quarkus:
        datasource:
            db-kind: h2
            jdbc:
                url: jdbc:h2:file:./target/h2db;DB_CLOSE_DELAY=-1
    
'%drop-create':
    quarkus:
        hibernate-orm:
            database:
                generation: drop-and-create
    liquibase:
        migrate-at-start: false

quarkus:
    datasource:
        db-kind: postgresql
        jdbc:
            url: jdbc:postgresql://${DB_HOST:localhost}:5432/katalog
        password: password
        username: postgres
    devservices:
        enabled: false
    hibernate-orm:
        database:
            generation: validate
    liquibase:
        change-log: db/changelog/db.changelog-root.xml
        migrate-at-start: true
