quarkus:
    datasource:
        db-kind: h2
        jdbc:
            url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    hibernate-orm:
        active: true
        database:
            generation: drop-and-create
        log:
            bind-parameters: true
            sql: true
    liquibase:
        migrate-at-start: false
    log:
        category:
            '"org.hibernate.type.descriptor.sql"':
                  level: TRACE
            '"organisationen.*"':
                  level: TRACE
        console:
            level: TRACE
        level: INFO
        min-level: TRACE
